package org.example.flights;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-06-26T19:03:36.284+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.example.org/Flights/", name = "Flights")
@XmlSeeAlso({ObjectFactory.class})
public interface Flights {

    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/Flights/NewOperation")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/Flights/", className = "org.example.flights.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/Flights/", className = "org.example.flights.NewOperationResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String newOperation(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
